# Service for api app 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spacelama-api
  name: spacelama-api
spec:
  selector:
    app: spacelama-api
  ports:
  - name: "9000"
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP
status:
  loadBalancer: {}
---
# Deployment for api app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacelama-api
spec:
  selector:
    matchLabels:
      app: spacelama-api
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spacelama-api
    spec:
      containers:
      - image: spacelama/api:latest
        imagePullPolicy: IfNotPresent
        name: spacelama-api
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
