apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 443
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: spacelama/web:latest
        name: spacelama-web
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
