# mongo db claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-claim
  labels:
    type: Database
    app: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
status: {}