# Service for mongo app 
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    port: "27017"
    app: "mongo"
spec:
  selector:
    app: SmartSearch
    tier: backend
  ports:
  - protocol: TCP
    name: mongo
    port: 27017
    targetPort: 27017
  type: ClusterIP