apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  creationTimestamp: null
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: spacelama/web:dev
        name: spacelama-web
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
