apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost
  name: ghost
spec:
  ports:
  - name: "2368"
    port: 2368
    targetPort: 2368
  selector:
    app: ghost
  type: LoadBalancer
status:
  loadBalancer: {}