apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: ghost-claim
spec:
  volumeName: pv-ghost
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
status: {}