# pods/storage/pv-claim.yaml  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ghost
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/docker/ghost/"