# Deployment of the backend app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacelama-api
  labels:
    stage: dev
spec:
  selector:
    matchLabels:
      stage: dev
  template:
    metadata:
      labels:
        stage: dev
    spec:
      containers:
      - image: spacelama/api-go:dev
        name: spacelama-api