# Deployment of the frontend app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    stage: dev
spec:
  selector:
    matchLabels:
      stage: dev
  template:
    metadata:
      labels:
        stage: dev
    spec:
      containers:
      - image: spacelama/web:dev
        name: web