apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    port: "443"
    app: "nginx"
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: SmartSearch
    tier: frontend
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer