apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: SmartSearch
    tier: frontend
spec:
  selector:
    matchLabels:
      app: SmartSearch
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: SmartSearch
        tier: frontend
    spec:
      containers:
      - image: spacelama/web:dev
        name: spacelama-web
        ports:
        - containerPort: 443
      restartPolicy: Always
status: {}