version: "3"

services:
  web:
    image : spacelama/web:latest
    depends_on:
      - "api"
    ports:
      - "4200:4200"

  api:
    image: spacelama/api:latest
    depends_on:
      - "mongo"
    links:
      - "mongo:mongo"
    ports:
      - "9000:9000"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
    - "27017:27017"