# Deployment of the backend app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacelama-api
spec:
  selector:
    matchLabels:
      app: spacelama-api
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spacelama-api
    spec:
      containers:
      - image: spacelama/api-go:latest
        imagePullPolicy: IfNotPresent
        name: spacelama-api
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
