apiVersion: v1
kind: Namespace
metadata:
  name: smartsearch
---
apiVersion: v1
kind: Service
metadata:
  namespace: smartsearch
  name: dev-smartsearch-web
  labels:
    app: smartSearch
    stage: development
    tier: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: smartSearch
    stage: development
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smartsearch
  labels:
    app: smartSearch
    stage: development
    tier: frontend
  name: dev-smartsearch-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: smartSearch
      stage: development
      tier: frontend
  template:
    metadata:
      labels:
        app: smartSearch
        stage: development
        tier: frontend
    spec:
      containers:
        - image: gcr.io/spacelama/github.com/doudidas/smartsearchweb:dev
          imagePullPolicy: Always
          name: smartsearch-web
      restartPolicy: Always
status: {}