# Deployment of the frontend app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    stage: production
spec:
  selector:
    matchLabels:
      stage: production
  template:
    metadata:
      labels:
        stage: production
    spec:
      containers:
      - image: spacelama/web:latest
        name: web