apiVersion: v1
kind: Namespace
metadata:
  name: smartsearch
---
apiVersion: v1
kind: Service
metadata:
  namespace: smartsearch
  name: dev-smartsearch-api
  labels:
    app: smartSearch
    stage: development
    tier: backend
spec:
  ports:
    - name: gin-gonic
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: smartSearch
    stage: development
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smartsearch
  labels:
    app: smartSearch
    stage: development
    tier: backend
  name: dev-smartsearch-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: smartSearch
      stage: development
      tier: backend
  template:
    metadata:
      labels:
        app: smartSearch
        stage: development
        tier: backend
    spec:
      containers:
        - image: spacelama/api-go:dev
          imagePullPolicy: Always
          name: smarsearch-api
          env:
            - name:  MONGO_HOSTNAME
              value: dev-smartsearch-db.smartsearch.svc.cluster.local