apiVersion: v1
kind: Namespace
metadata:
  name: smartsearch
---
apiVersion: v1
kind: Service
metadata:
  namespace: smartsearch
  name: smartsearch-db
  labels:
    app: smartSearch
    stage: production
    tier: database
spec:
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: smartSearch
    stage: production
    tier: database
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: smartsearch-db
  namespace: smartsearch
  labels:
    app: smartSearch
    stage: production
    tier: database
spec:
  serviceName: smartsearch-db
  replicas: 1
  template:
    metadata:
      labels:
        app: smartSearch
        stage: production
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi