# Deployment of the mongo app 
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:latest
        imagePullPolicy: IfNotPresent
        name: ghost
        ports:
        - containerPort: 2368
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: pv-ghost
      restartPolicy: Always
      volumes:
      - name: pv-ghost
        persistentVolumeClaim:
          claimName: ghost-claim
status: {}