apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongo
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: mongo
  targetCPUUtilizationPercentage: 30