# pods/storage/pv-claim.yaml  
kind: PersistentVolume
metadata:
  name: pv-volume-configdb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/configdb"
---
# Service for mongo app 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  creationTimestamp: null
  name: mongo
  selector:
    app: mongo
  type: LoadBalancer
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
status:
  loadBalancer: {}
---
# Deployment of the mongo app 
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/configdb
          name: mongo-claim-config
        - mountPath: /data/db
          name: mongo-claim-db
      restartPolicy: Always
      volumes:
      - name: mongo-claim-config
        persistentVolumeClaim:
          claimName: mongo-claim-config
      - name: mongo-claim-db
        persistentVolumeClaim:
          claimName: mongo-claim-db
status: {}
