apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spacelama-api
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spacelama-api
  targetCPUUtilizationPercentage: 50