# pods/storage/pv-claim.yaml  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ghost
spec:
  storageClassName: null
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/docker/ghost/"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: ghost-claim
spec:
  volumeName: pv-ghost
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---


