apiVersion: v1
kind: Service
metadata:
  labels:
    port: "9000"
    app: "go-gin"
  name: spacelama-api
spec:
  selector:
    app: SmartSearch
    tier: backend
  ports:
  - name: "9000"
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP