apiVersion: v1
kind: Namespace
metadata:
  name: spacelama
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: spacelama
  name: localhost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: smartsearch-web
          servicePort: 80
      - path: /api
        backend:
          serviceName: smartsearch-api
          servicePort: 9000