# pods/storage/pv-claim.yaml  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"